const GAME_TICK_SECONDS = 0.5;
const DILEMMA_LOCATION_DESTRUCT_ANIMATION_TIME = 0.3;

const INITIAL_EMISSIONS = 50;
const INITIAL_MONEY = 50;
const INITIAL_QUALITY_OF_LIFE = 50;
const INITIAL_YEAR = 2022;

const MAX_EMISSIONS = 100;
const MAX_MONEY = 100;
const MAX_QOF = 100;
const MAX_YEAR = 2050;


export default {
    GAME_TICK_SECONDS,
    DILEMMA_LOCATION_DESTRUCT_ANIMATION_TIME,
    INITIAL_EMISSIONS,
    INITIAL_MONEY,
    INITIAL_QUALITY_OF_LIFE,
    INITIAL_YEAR,
    MAX_EMISSIONS,
    MAX_MONEY,
    MAX_QOF,
    MAX_YEAR,
}