const GAME_TICK_SECONDS = 0.5;
const DILEMMA_LOCATION_DESTRUCT_ANIMATION_TIME = 0.3;

const INITIAL_EMISSIONS = 50;
const INITIAL_MONEY = 50;
const INITIAL_QUALITY_OF_LIFE = 50;
const INITIAL_YEAR = 2042;

const MAX_EMISSIONS = 100;
const MAX_MONEY = 100;
const MAX_QOF = 100;
const MAX_YEAR = 2050;

const MIN_YEAR = 2022;
const MIN_QOF = 0;
const MIN_MONEY = 0;
const MIN_EMISSIONS = 0;

const YEAR_HEB_NAME = "שנה";
const QOF_HEB_NAME = "איכות חיים";
const MONEY_HEB_NAME = "כסף";
const EMISSIONS_HEB_NAME = "גזי חממה";

// To represent for effects which category
const YEAR_METRIC = 1;
const QOF_METRIC = 2;
const MONEY_METRIC = 3;
const EMISSIONS_METRIC = 4;


const METRIC_TO_COLOR = {
    [YEAR_METRIC]: "red",
    [QOF_METRIC]: "blue",
    [MONEY_METRIC]: "green",
    [EMISSIONS_METRIC]: "black",
}
const EFFECT_ANIMATINO_TIME = 1.5;

export default {
    GAME_TICK_SECONDS,
    DILEMMA_LOCATION_DESTRUCT_ANIMATION_TIME,
    INITIAL_EMISSIONS,
    INITIAL_MONEY,
    INITIAL_QUALITY_OF_LIFE,
    INITIAL_YEAR,
    MAX_EMISSIONS,
    MAX_MONEY,
    MAX_QOF,
    MAX_YEAR,
    MIN_YEAR,
    MIN_EMISSIONS,
    MIN_MONEY,
    MIN_QOF,
    YEAR_HEB_NAME,
    QOF_HEB_NAME,
    MONEY_HEB_NAME,
    EMISSIONS_HEB_NAME,
    YEAR_METRIC,
    QOF_METRIC,
    MONEY_METRIC,
    EMISSIONS_METRIC,
    METRIC_TO_COLOR,
    EFFECT_ANIMATINO_TIME
}